# Generated by Django 4.2.5 on 2023-09-17 15:53

from django.db import migrations, models
import metadataWiperBackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadataWiperBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOCXModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=metadataWiperBackend.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=metadataWiperBackend.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='PDFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=metadataWiperBackend.models.upload_to)),
            ],
        ),
    ]
