# Generated by Django 4.2.5 on 2023-09-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadataWiperBackend', '0003_jpegmodel_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jpegmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='jpegmodel',
            name='title',
        ),
    ]
