# Generated by Django 4.2.5 on 2023-09-17 23:49

from django.db import migrations, models
import metadataWiperBackend.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadataWiperBackend', '0004_remove_jpegmodel_content_remove_jpegmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='XLSXModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xlsx_file', models.FileField(upload_to=metadataWiperBackend.models.upload_to)),
            ],
        ),
        migrations.DeleteModel(
            name='ExcelModel',
        ),
    ]
