# Generated by Django 4.2.5 on 2023-09-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadataWiperBackend', '0005_xlsxmodel_delete_excelmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docxmodel',
            old_name='file',
            new_name='docx_file',
        ),
    ]
