# Generated by Django 4.2.5 on 2023-09-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadataWiperBackend', '0006_rename_file_docxmodel_docx_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfmodel',
            old_name='file',
            new_name='pdf_file',
        ),
    ]
